server:
  contextPath: null
  address: 0.0.0.0
  port: 8080
spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  contextPath: null
  address: 0.0.0.0
  port: 8080
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:mysql://localhost:3306/nokia_db
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    max-active: 50
    initial-size: 5
    max-idle: 10
    min-idle: 5
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
files-path: rapports/